import { createClient } from "@/lib/supabase/server";
import Link from "next/link";
import { Bell, CheckCircle2, Clock3 } from "lucide-react";

export default async function NotificationsPage() {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();

  if (!user) return <main className="nexus-page"><h1>Notifications</h1><p>Unauthorized</p></main>;

  const { data: profile } = await supabase.from("users").select("email").eq("user_id", user.id).maybeSingle();
  const { data } = await supabase
    .from("notifications")
    .select("notification_id,kind,project_id,title,message,due_date,created_at,read_at")
    .eq("recipient_email", profile?.email || "")
    .order("created_at", { ascending: false })
    .limit(100);

  const rows = data ?? [];
  const unread = rows.filter((row) => !row.read_at).length;

  return (
    <main className="nexus-page notifications-workspace">
      <header className="nexus-page-head">
        <div>
          <div className="eyebrow">ACTIVITY MANAGEMENT</div>
          <h1>Notifications</h1>
          <p>CRM reminders and alerts generated by follow-up and automation workflows.</p>
        </div>
        <div className="nexus-head-actions">
          <span className="workspace-chip"><Bell size={14} /> {unread} unread</span>
        </div>
      </header>

      <section className="dashboard-stat-grid notification-kpis">
        <div className="nexus-stat-card"><div className="nexus-stat-icon blue"><Bell size={18} /></div><div><span>Total</span><strong>{rows.length}</strong><small>Recent notifications</small></div></div>
        <div className="nexus-stat-card"><div className="nexus-stat-icon amber"><Clock3 size={18} /></div><div><span>Unread</span><strong>{unread}</strong><small>Require attention</small></div></div>
        <div className="nexus-stat-card"><div className="nexus-stat-icon green"><CheckCircle2 size={18} /></div><div><span>Read</span><strong>{rows.length - unread}</strong><small>Already reviewed</small></div></div>
      </section>

      <section className="nexus-card">
        <div className="nexus-table-wrap">
          <table className="nexus-table">
            <thead><tr><th>Due</th><th>Kind</th><th>Title</th><th>Project</th><th>Message</th><th>Status</th></tr></thead>
            <tbody>
              {rows.map((row) => (
                <tr key={row.notification_id}>
                  <td>{row.due_date || "—"}</td>
                  <td>{row.kind}</td>
                  <td>{row.title}</td>
                  <td>{row.project_id ? <Link href={"/projects/" + encodeURIComponent(row.project_id)}>{row.project_id}</Link> : "—"}</td>
                  <td>{row.message}</td>
                  <td><span className={row.read_at ? "status-badge" : "status-badge status-warning"}>{row.read_at ? "Read" : "Unread"}</span></td>
                </tr>
              ))}
              {rows.length === 0 && <tr><td colSpan={6}><div className="nexus-empty-inline">No notifications.</div></td></tr>}
            </tbody>
          </table>
        </div>
      </section>
    </main>
  );
}
