"use client";
import { useMemo, useState } from "react";
import { CalendarClock, AlertCircle, CheckCircle2, Plus, X } from "lucide-react";
import { addFollowUp, completeFollowUp } from "./actions";
const TYPES=["Call","Visit","Email","Meeting","WhatsApp","Other"];
export default function FollowUpsClient({projects,followUps}:{projects:any[];followUps:any[]}) {
  const [completeOpen,setCompleteOpen]=useState<string|null>(null); const [completeType,setCompleteType]=useState("Call"); const [completeResult,setCompleteResult]=useState(""); const [completeNotes,setCompleteNotes]=useState(""); const [completeNextDate,setCompleteNextDate]=useState(""); const [completeNextType,setCompleteNextType]=useState("Call");
  const [projectId,setProjectId]=useState(""); const [date,setDate]=useState(""); const [time,setTime]=useState(""); const [type,setType]=useState("Call"); const [notes,setNotes]=useState(""); const [nextDate,setNextDate]=useState(""); const [nextType,setNextType]=useState("Call"); const [busy,setBusy]=useState(false); const [message,setMessage]=useState("");
  const today=new Date().toISOString().slice(0,10);
  const rows=useMemo(()=>followUps.filter(f=>!f.completed_at).map(f=>({...f,project:projects.find(p=>p.project_id===f.project_id)})),[followUps,projects]);
  const overdue=rows.filter(f=>f.followup_date && f.followup_date<today).length; const todayCount=rows.filter(f=>f.followup_date===today).length;
  async function save(){if(!projectId||!date){setMessage("Project and date are required.");return}setBusy(true);setMessage("");try{await addFollowUp({projectId,date,time,type,notes,nextActionDate:nextDate,nextActionType:nextDate?nextType:undefined});setMessage("Follow-up saved.");window.location.reload()}catch(e:any){setMessage(e.message||"Save failed.");setBusy(false)}}
  async function complete(id:string){if(!completeResult.trim()&&!completeNotes.trim()){setMessage("Result or notes are required.");return}setBusy(true);try{await completeFollowUp({followUpId:id,type:completeType,result:completeResult.trim(),notes:completeNotes.trim(),nextActionDate:completeNextDate||undefined,nextActionType:completeNextDate?completeNextType:undefined});setCompleteOpen(null);window.location.reload()}catch(e:any){setMessage(e.message||"Completion failed.");setBusy(false)}}
  return <div><div className="dashboard-stat-grid followup-kpis"><div className="nexus-stat-card"><div className="nexus-stat-icon blue"><CalendarClock size={18}/></div><div><span>Today</span><strong>{todayCount}</strong><small>Due today</small></div></div><div className="nexus-stat-card"><div className="nexus-stat-icon red"><AlertCircle size={18}/></div><div><span>Overdue</span><strong>{overdue}</strong><small>Needs attention</small></div></div><div className="nexus-stat-card"><div className="nexus-stat-icon green"><CheckCircle2 size={18}/></div><div><span>Open</span><strong>{rows.length}</strong><small>Pending activities</small></div></div></div><section className="nexus-card followup-create"><div className="pipeline-kpi"><span>Today</span><strong>{todayCount}</strong></div><div className="pipeline-kpi"><span>Overdue</span><strong>{overdue}</strong></div><div className="pipeline-kpi"><span>Open</span><strong>{rows.length}</strong></div>
  <div className="section-head"><div><h2>Create activity</h2><p className="muted">Schedule the next customer touchpoint.</p></div><Plus size={18}/></div><div className="nexus-form-grid">
  <label>Project<select value={projectId} onChange={e=>setProjectId(e.target.value)}><option value="">Select project</option>{projects.map(p=><option key={p.project_id} value={p.project_id}>{p.project_name} — {p.client}</option>)}</select></label>
  <label>Date<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Time<input type="time" value={time} onChange={e=>setTime(e.target.value)}/></label>
  <label>Type<select value={type} onChange={e=>setType(e.target.value)}>{TYPES.map(t=><option key={t}>{t}</option>)}</select></label>
  <label>Next Action Date<input type="date" value={nextDate} onChange={e=>setNextDate(e.target.value)}/></label>
  <label>Next Action Type<select value={nextType} onChange={e=>setNextType(e.target.value)}>{TYPES.map(t=><option key={t}>{t}</option>)}</select></label>
  <label className="full">Notes<textarea value={notes} onChange={e=>setNotes(e.target.value)} rows={3}/></label></div><div style={{display:"flex",gap:10,alignItems:"center"}}><button className="nexus-primary" onClick={save} disabled={busy}>Save Follow Up</button>{message&&<span>{message}</span>}</div></section>
  <section className="nexus-card"><h2>Open Follow Ups</h2><div className="nexus-table-wrap"><table className="nexus-table"><thead><tr><th>Date</th><th>Project</th><th>Client</th><th>Type</th><th>Next Action</th><th></th></tr></thead><tbody>{rows.map(f=><tr key={f.followup_id}><td>{f.followup_date}{f.followup_time?" "+f.followup_time:""}</td><td>{f.project?.project_name||f.project_id}</td><td>{f.project?.client||"—"}</td><td>{f.followup_type}</td><td>{f.next_action_date||"—"}</td><td><button className="nexus-secondary" onClick={()=>{setCompleteOpen(f.followup_id);setCompleteType(f.followup_type||"Call");setCompleteResult(f.result||"");setCompleteNotes("");setCompleteNextDate("");setCompleteNextType("Call");setMessage("")}} disabled={busy}><CheckCircle2 size={14}/> Complete</button></td></tr>)}{rows.length===0&&<tr><td colSpan={6}>No open follow-ups.</td></tr>}</tbody></table></div></section>{completeOpen&&<div className="nexus-modal-backdrop" role="dialog" aria-modal="true"><div className="nexus-modal"><div className="nexus-modal-head"><div><div className="eyebrow">ACTIVITY MANAGEMENT</div><h3>Complete Follow-up</h3><p>Capture the outcome and schedule the next customer action.</p></div><button className="nexus-icon-button" onClick={()=>setCompleteOpen(null)} aria-label="Close"><X size={18}/></button></div><div className="nexus-form-grid"><label>Follow-up Type<select value={completeType} onChange={e=>setCompleteType(e.target.value)}>{TYPES.map(t=><option key={t}>{t}</option>)}</select></label><label>Result<input value={completeResult} onChange={e=>setCompleteResult(e.target.value)} placeholder="What was the outcome?"/></label><label style={{gridColumn:"1/-1"}}>Notes<textarea value={completeNotes} onChange={e=>setCompleteNotes(e.target.value)} rows={3}/></label><label>Next Action Date<input type="date" value={completeNextDate} onChange={e=>setCompleteNextDate(e.target.value)}/></label><label>Next Action Type<select value={completeNextType} disabled={!completeNextDate} onChange={e=>setCompleteNextType(e.target.value)}>{TYPES.map(t=><option key={t}>{t}</option>)}</select></label></div><div className="nexus-modal-foot"><button className="nexus-secondary" onClick={()=>setCompleteOpen(null)}>Cancel</button><button className="nexus-primary" disabled={busy} onClick={()=>complete(completeOpen)}><CheckCircle2 size={14}/>{busy?"Saving…":"Complete Follow-up"}</button></div></div></div>}</div>;
}
