"use client";
import Link from "next/link";
import { useMemo, useState } from "react";
import { ChevronLeft, ChevronRight, Filter, Search, SlidersHorizontal } from "lucide-react";
const STAGES=["Tender","Tender – High Probability","In Hand","Negotiation"];
function money(v:number){return new Intl.NumberFormat("en-EG",{style:"currency",currency:"EGP",maximumFractionDigits:0}).format(v||0)}
export default function ProjectsClient({projects}:{projects:any[]}){
 const [q,setQ]=useState(()=>typeof window==="undefined"?"":new URLSearchParams(window.location.search).get("search")||"");const [stage,setStage]=useState("All");const [type,setType]=useState("All");const [location,setLocation]=useState("All");const [sort,setSort]=useState("Highest Value");const [page,setPage]=useState(1);const [size,setSize]=useState(30);
 const types=Array.from(new Set(projects.map(p=>p.project_type).filter(Boolean))).sort();const locations=Array.from(new Set(projects.map(p=>p.location).filter(Boolean))).sort();
 const filtered=useMemo(()=>{let x=projects.filter(p=>STAGES.includes(p.current_action));const s=q.trim().toLowerCase();if(s)x=x.filter(p=>[p.project_id,p.project_name,p.client,p.consultant].some(v=>String(v||"").toLowerCase().includes(s)));if(stage!=="All")x=x.filter(p=>p.current_action===stage);if(type!=="All")x=x.filter(p=>p.project_type===type);if(location!=="All")x=x.filter(p=>p.location===location);x.sort((a,b)=>sort==="Highest Value"?Number(b.estimated_value||0)-Number(a.estimated_value||0):sort==="Next Follow Up"?String(a.next_followup_date||"9999").localeCompare(String(b.next_followup_date||"9999")):sort==="Recent Touch"?String(b.last_followup_date||"").localeCompare(String(a.last_followup_date||"")):String(b.updated_at||"").localeCompare(String(a.updated_at||"")));return x},[projects,q,stage,type,location,sort]);
 const total=filtered.length;const pages=Math.max(1,Math.ceil(total/size));const rows=filtered.slice((page-1)*size,page*size);
 return <div className="projects-workspace">
  <div className="pipeline-kpis">{STAGES.map((s,i)=><div className="pipeline-kpi" key={s}><span className={"stage-dot s"+i}/><div><span>{s}</span><strong>{projects.filter(p=>p.current_action===s).length}</strong></div></div>)}</div>
  <section className="nexus-filter-panel"><div className="filter-title"><div><SlidersHorizontal size={16}/><strong>Project filters</strong></div><span>{total} results</span></div><div className="nexus-form-grid">
   <label className="search-field"><span>Search</span><div><Search size={16}/><input value={q} onChange={e=>{setQ(e.target.value);setPage(1)}} placeholder="Project, client or consultant"/></div></label>
   <label><span>Stage</span><select value={stage} onChange={e=>{setStage(e.target.value);setPage(1)}}><option>All</option>{STAGES.map(s=><option key={s}>{s}</option>)}</select></label>
   <label><span>Project Type</span><select value={type} onChange={e=>{setType(e.target.value);setPage(1)}}><option>All</option>{types.map(s=><option key={s}>{s}</option>)}</select></label>
   <label><span>Location</span><select value={location} onChange={e=>{setLocation(e.target.value);setPage(1)}}><option>All</option>{locations.map(s=><option key={s}>{s}</option>)}</select></label>
   <label><span>Sort</span><select value={sort} onChange={e=>setSort(e.target.value)}><option>Highest Value</option><option>Next Follow Up</option><option>Recent Touch</option><option>Newest</option></select></label>
   <label><span>Per page</span><select value={size} onChange={e=>{setSize(Number(e.target.value));setPage(1)}}>{[15,30,50,100].map(n=><option key={n}>{n}</option>)}</select></label>
  </div></section>
  <section className="nexus-card project-table-card"><div className="table-toolbar"><div><strong>Active projects</strong><span>Live CRM pipeline</span></div><div className="table-toolbar-meta"><Filter size={15}/> {total} projects</div></div><div className="nexus-table-wrap"><table className="nexus-table"><thead><tr><th>PROJECT</th><th>CLIENT</th><th>STAGE</th><th>EST. VALUE</th><th>NEXT FOLLOW UP</th></tr></thead><tbody>{rows.map(p=><tr key={p.project_id}><td><Link className="project-link" href={"/projects/"+encodeURIComponent(p.project_id)}><span className="project-id">{p.project_id}</span><strong>{p.project_name||"Untitled project"}</strong></Link></td><td>{p.client||"—"}</td><td><span className={"stage-pill s"+STAGES.indexOf(p.current_action)}>{p.current_action}</span></td><td className="money-cell">{money(Number(p.estimated_value)||0)}</td><td>{p.next_followup_date||"—"}</td></tr>)}{!rows.length&&<tr><td colSpan={5}><div className="nexus-empty-inline">No matching active projects.</div></td></tr>}</tbody></table></div><div className="pagination"><span>Showing {rows.length?((page-1)*size+1):0}–{Math.min(page*size,total)} of {total}</span><div><button className="icon-button" disabled={page<=1} onClick={()=>setPage(page-1)}><ChevronLeft size={16}/></button><span>Page {page} of {pages}</span><button className="icon-button" disabled={page>=pages} onClick={()=>setPage(page+1)}><ChevronRight size={16}/></button></div></div></section>
 </div>;
}