"use client";
import Link from "next/link";
import { useMemo, useState } from "react";
const STAGES=["Tender","Tender – High Probability","In Hand","Negotiation"];
function money(v:number){return new Intl.NumberFormat("en-EG",{style:"currency",currency:"EGP",maximumFractionDigits:0}).format(v||0)}
export default function ProjectsClient({projects}:{projects:any[]}){
 const [q,setQ]=useState("");const [stage,setStage]=useState("All");const [type,setType]=useState("All");const [location,setLocation]=useState("All");const [sort,setSort]=useState("Highest Value");const [page,setPage]=useState(1);const [size,setSize]=useState(30);
 const types=Array.from(new Set(projects.map(p=>p.project_type).filter(Boolean))).sort();const locations=Array.from(new Set(projects.map(p=>p.location).filter(Boolean))).sort();
 const filtered=useMemo(()=>{let x=projects.filter(p=>STAGES.includes(p.current_action));const s=q.trim().toLowerCase();if(s)x=x.filter(p=>[p.project_id,p.project_name,p.client,p.consultant].some(v=>String(v||"").toLowerCase().includes(s)));if(stage!=="All")x=x.filter(p=>p.current_action===stage);if(type!=="All")x=x.filter(p=>p.project_type===type);if(location!=="All")x=x.filter(p=>p.location===location);x.sort((a,b)=>sort==="Highest Value"?Number(b.estimated_value||0)-Number(a.estimated_value||0):sort==="Next Follow Up"?String(a.next_followup_date||"9999").localeCompare(String(b.next_followup_date||"9999")):sort==="Recent Touch"?String(b.last_followup_date||"").localeCompare(String(a.last_followup_date||"")):String(b.updated_at||"").localeCompare(String(a.updated_at||"")));return x},[projects,q,stage,type,location,sort]);
 const total=filtered.length;const pages=Math.max(1,Math.ceil(total/size));const rows=filtered.slice((page-1)*size,page*size);
 return <div><div className="pipeline-kpis">{STAGES.map(s=><div className="pipeline-kpi" key={s}><span>{s}</span><strong>{projects.filter(p=>p.current_action===s).length}</strong></div>)}</div>
 <section className="nexus-card"><div className="nexus-form-grid"><label>Search<input value={q} onChange={e=>{setQ(e.target.value);setPage(1)}} placeholder="Project / Client / Consultant"/></label><label>Stage<select value={stage} onChange={e=>{setStage(e.target.value);setPage(1)}}><option>All</option>{STAGES.map(s=><option key={s}>{s}</option>)}</select></label><label>Project Type<select value={type} onChange={e=>{setType(e.target.value);setPage(1)}}><option>All</option>{types.map(s=><option key={s}>{s}</option>)}</select></label><label>Location<select value={location} onChange={e=>{setLocation(e.target.value);setPage(1)}}><option>All</option>{locations.map(s=><option key={s}>{s}</option>)}</select></label><label>Sort<select value={sort} onChange={e=>setSort(e.target.value)}><option>Highest Value</option><option>Next Follow Up</option><option>Recent Touch</option><option>Newest</option></select></label><label>Per Page<select value={size} onChange={e=>{setSize(Number(e.target.value));setPage(1)}}>{[15,30,50,100].map(n=><option key={n}>{n}</option>)}</select></label></div></section>
 <section className="nexus-card"><div className="nexus-table-wrap"><table className="nexus-table"><thead><tr><th>ID</th><th>Project</th><th>Client</th><th>Stage</th><th>Value</th><th>Next Follow Up</th></tr></thead><tbody>{rows.map(p=><tr key={p.project_id}><td><Link href={"/projects/"+encodeURIComponent(p.project_id)}>{p.project_id}</Link></td><td>{p.project_name||"—"}</td><td>{p.client||"—"}</td><td>{p.current_action}</td><td>{money(Number(p.estimated_value)||0)}</td><td>{p.next_followup_date||"—"}</td></tr>)}{!rows.length&&<tr><td colSpan={6}>No matching active projects.</td></tr>}</tbody></table></div><div style={{display:"flex",justifyContent:"space-between",marginTop:12}}><span>{total} matching projects</span><div><button className="nexus-secondary" disabled={page<=1} onClick={()=>setPage(page-1)}>Previous</button> <span> {page}/{pages} </span><button className="nexus-secondary" disabled={page>=pages} onClick={()=>setPage(page+1)}>Next</button></div></div></section></div>;
}